package io.skysail.server.app.notes.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import io.skysail.domain.Identifiable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
@NoArgsConstructor
@DynamoDBTable(tableName = "notes")
public class AwsNote implements Identifiable {

    public enum AwsStatus {
        CREATED,
        UPDATED,
        DELETED
    }

    private String id;

    @DynamoDBHashKey(attributeName = "noteUuid")
	//@DynamoDBAutoGeneratedKey
	private String noteUuid;

//	@DynamoDBAttribute(attributeName="userUuid")
//	private String userUuid;

	@DynamoDBAttribute(attributeName="entity")
	private String entity;

	@DynamoDBAttribute(attributeName="tstamp")
	private long tstamp;

	@DynamoDBAttribute(attributeName="type")
	private String type;


}