bootstrap_mainContent(user, converter, messages, model) ::= <<

    <div class="row main-row fill">
    <div class="col-sm-2 sidebar hidden-xs" style="height:100%">
        <h3>Navigation</h3>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
    </div>
    <div class="col-sm-10 col-xs-12 main-content-area">
        <h1 class="page-header">Content</h1>
        <p>Content</p>
    </div>
</div>

 
>>
