sui_head() ::= <<
	<!-- Standard Meta -->
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
	
	<!-- Site Properties -->
    <title>$messages.("productName").translated$</title>
	
    <link rel="shortcut icon" href="/webapp/favicon.ico" type="image/x-icon" >
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    
    <link rel="stylesheet" type="text/css" href="/_ui/semanticui/2.2.6/semantic.min.css">
	<script src="/_ui/semanticui/2.2.6/semantic.min.js"></script>
	
    <style type="text/css">
    
 	   html, body {
		    height: 100%;
		}
		
		.ui.grid {
		    height: 100%;    
		}
	  body {
	    background-color: #FFFFFF;
	  }
	  .ui.menu .item img.logo {
	    margin-right: 1.5em;
	  }
	  .main.container {
	    margin-top: 7em;
	  }
	  .wireframe {
	    margin-top: 2em;
	  }
	  .ui.footer.segment {
	    margin: 5em 0em 0em;
	    padding: 5em 0em;
	  }
    </style>
	
>>