bst_head(converter) ::= <<
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Skysail</title>
  
  <link rel="shortcut icon" href="/webapp/favicon.ico" type="image/x-icon" >
  <link rel="stylesheet"    href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css" async>
  <link rel="stylesheet"    href="/_ui/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet"    href="https://fonts.googleapis.com/css?family=Inconsolata|Roboto|Slabo+27px" async>

  <script type="text/javascript" src="/_ui/jquery/3.1.1/jquery-3.1.1.min.js"></script>

  <link href="/webapp/css/contextMenu/jquery.contextMenu.css" rel="stylesheet" type="text/css" async />
  <script type="text/javascript" src="/webapp/js/contextMenu/jquery.contextMenu.js" async></script>

  <script type="text/javascript" src="/_polymer/bower_components/noty/js/noty/packaged/jquery.noty.packaged.min.js"></script>
  <script type="text/javascript" src="/_ui/bootstrap/sky-bst/noty.defaults.js"></script>
    
  <script type="text/javascript" src="/_ui/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/_polymer/bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
  
  <link rel="import"        href="/_ui/bootstrap/sky-bst/imports.html">
  <link rel="stylesheet"    href="/_ui/bootstrap/sky-bst/skysail.css">
  
  <link rel="stylesheet" type="text/css" href="/webapp/css/hover/hover-min.css">
  
  <!-- UI Extensions from bundles (if any) -->
  $converter.uiPolymerExtensions: {extension | <link rel="import" href="$extension$">};separator="\n"$
>>